spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    schema:
      - classpath:/sql/schema.sql
    data:
      - classpath:/sql/data.sql
    batch:
      initialize-schema: always
  jpa:database-platform: org.hibernate.dialect.H2Dialect
